### ISSUE TITLE
Games do not move when window is resized and there is room to the left

### ISSUE THREAD

**Issue by MrIlliteracy** [RedDuckss/CemuManager#10]
![](http://i.imgur.com/uJzapi2.gif)

**Comment by RedDuckss** [comment]
Fixed in v0.1.2

**Comment by MrIlliteracy** [comment]
Not fixed for me?

**Comment by RedDuckss** [comment]
Ensure you are using the latest copy of the repo and provide a screenshot of the error in the latest version, please. I cannot replicate this bug.

**Comment by MrIlliteracy** [comment]
Its the same as the gif above, i know i was using the latest version (with a clean install) because i was developing on it

**Comment by RedDuckss** [comment]
Will look in to this further. Could possibly be caused by differing screen resolutions and sizes, as I cannot replicate this issue on any build.

**Comment by MrIlliteracy** [comment]
Yeah thats what I was thinking, my screen res is 1080p

**Comment by RedDuckss** [comment]
I use a 4K LG TV. This is most likely the cause.
