### ISSUE TITLE
Random game data download error on certain games

### ISSUE THREAD

**Issue by RedDuckss** [RedDuckss/CemuManager#12]
This is a mirror of a bug DMed to me:

Certain games seem to throw errors when downloading detailed information about the game. The only report of this happening throws the error when getting the games ESRB rating (as per the line number thrown in the error), and the game throwing the error is unknown.

Original message from Reddit DM:
```
Hello, I know this might not be the best way to report a bug/error but I thought i may as well tell you. I have been receiving an error whenever I go to select where my games are stored. After i select the location, it starts to download the data, The give me a number of popup error messages that read "cannot read property '0' of undefined"
Here is the image of the error: http://imgur.com/a/yMpYM
Also, thank you for creating an awesome looking frontend for cemu!
```
![errorimage](http://i.imgur.com/QKFgAHL.jpg)

**Comment by LWL285** [comment]
Reddit user here,
Here are the list of games (all EU) 
-The Legend of Zelda Breath of the Wild 
-Captain Toad Treasure Tracker 
-Donkey Kong Country Tropical Freeze 
-Mario Kart 8 
-Mario party 10 
-New super Luigi U 
-Splatoon 
-Super Mario 3D World 
-Super Mario Maker 
-Super Smash Bros. for Wii U

**Comment by RedDuckss** [comment]
I believe I have tracked down the issue and see a possible fix. When downloading the data for `Mario party 10`, it does not return an ESRB rating. This matches up with the line in the error message, which deals with grabbing the games ESRB rating. Thankfully the ESRB rating is returned for `Mario party 10: Special Edition Bowser`, which I assume is the "same" game, and I am able to add a simple check for these types of issues.

**Comment by RedDuckss** [comment]
Update: This bug also seems to occur with `Super Mario Maker`, and the fix should also work for it (and future games with this issue) with no additional changes.

**Comment by RedDuckss** [comment]
I have pushed a possible fix to this issue (cannot test locally since I do not have the games which cause the error). The fix is applied to the `dev` branch of the repo, if you would like to download it and build from source (or run as dev, both are the same except dev has logging in cmd). If the error still persists please let me know. For now I will close this issue.
