### ISSUE TITLE
Not all Games show up.

### ISSUE THREAD

**Issue by davidevan84** [RedDuckss/CemuManager#16]
Not all games show up when it scans the folder initially.

**Comment by RedDuckss** [comment]
Would you mind rewriting this issue report in the correct format :P

![format](http://i.imgur.com/oKj9EFI.png)

**Comment by RedDuckss** [comment]
This issue should now be fixed as of the most recent release, which I just posted a few minutes ago. We have moved away from the old API in favor of a custom one which references games via title ID. All games should now appear in the list.
