### ISSUE TITLE
Should not ship releases with `data/cache`

### ISSUE THREAD

**Issue by SavageCore** [RedDuckss/CemuManager#2]
[v0.1.0](https://github.com/RedDuckss/CemuManager/releases/tag/v0.1.0) has `data\cache` folders populated resulting in broken images and no first run setup.

**Comment by RedDuckss** [comment]
This was an accident on my part. I forgot to remove the data after my initial testing, they weren't supposed to be there. I have now made a note about it on the release page. I am not at my house, so I cannot change the release itself at the moment. Sorry about that.
